FleekHQ/space-daemon

- core/textile/client/client_file.go
Not sure if this is really best practice, since it discards the context being passed. Pushing this as a hotfix so we can unblock testing. But will do a better refactor later: make both the context creation functions also take in an existing context and use that if supplied.
> Hotfix: Add bucket context with creds to get file operation

- app/app.go
- core/space/services/services_fs.go
- core/sync/sync.go
- core/textile/client/client.go
- core/textile/client/client_file.go
- core/textile/client/crud.go
- core/textile/listener/listener.go
* Updated base context creation helpers to take in an optional ctx variable
* Updated Textile client helpers to pass through ctx
Right now we have the single context being shared every where so things like Done signal are handled. Maybe for now this is okay and in the future we can design top down parallel contexts and how they interact if needed.
> Make Textile creds ctx creators take in an existing context

- examples/textileBucketsClient/sync-test/sync-test.go
- go.sum
This example reloads a key seed and thread ID and tries to add a file to the personal bucket. The file then shows up in the local UI.  While doing this test realized that for shared buckets we need a hybrid of local+remote so leverage the Textile synchronizing which we captured as the next TODO.
* Use hybrid local-remote thread for shared buckets
* Test sync between different users
> Example: Sync test for hub bucket

- .gitignore
- README.md
- cmd/space-poc/main.go
Related card:
https://app.clubhouse.io/terminalsystems/story/16670/daemon-stops-working-and-consumes-a-lot-of-cpu-after-a-while
Change Log:
* adds profiling tools to daemon to help research performance issues in the space app
> add profile debugging to main.go

- .gitignore
- core/textile/listener.go
NOTE: after testing with the profile analysis, i think we need to handle when the channel is closed by threads library to avoid being stuck on those go routines in an infinite loop. 
We still need to monitor the app and CPU is something else pops up, since its hard to replicate given that the usually could be related to threads side.
> possible fix for high CPU usage

- cmd/installer/main.go
- cmd/space-poc/main.go
- config/config.go
- config/json_config.go
- config/map_config.go
- core/env/env.go
- core/env/file_env.go
https://app.clubhouse.io/terminalsystems/story/16673/run-without-configuration-env-vars
change Log:
* Adds map backed implementation for config with default values
* Adds default env implementation
* removes JSON config file dependency from daemon and installer
* deprecated Implementation for Json backed config
TODO: move out of .env file by writing textile keys to store in installer and implement env that source from store
> add default values config

- cmd/space-poc/main.go
- config/config.go
- config/map_config.go
- core/env/env.go
- core/env/file_env.go
- core/store/store.go
https://app.clubhouse.io/terminalsystems/story/16814/store-hangs-on-startup
Change Log:
* With this change we can run the space binary with `-dev` flag to use the .env file in development environment
* Fix bugs with error checking on store bootstrap that could hang the daemon boot
> add dev mode and better store error checking on startup

- config/config.go
- core/textile/buckd.go
- go.mod
- go.sum
This PR allows us to configure the maximum number of open TCP connections created by textiles threads p2p connections.
By default the Maximum connection is set to 100, which is low enough to not reach the file descriptor limits on devices we've tested (currently macOS appears to default to 256 file descriptor limit).
NOTE: This PR modifies the textile dependency to use the version containing the fix in my fork. There is a PR open for it [here](https://github.com/textileio/textile/pull/261) to merge it to their release.
> Fix: Limit ThreadsDB p2p connection

- .github/workflows/test.yml
- core/libfuse/directory.go
- core/libfuse/files.go
- core/libfuse/vfs.go
- core/space/fuse/controller.go
- core/space/fuse/fs.go
- core/space/fuse/mount.go
- core/space/fuse/mount_windows.go
- core/watcher/blacklist.go
**CHANGELOG**
- Extract VFS into an interface
- Isolate initializing libfuse.NewVFSSystem() to only non-windows builds
- Enaables windows-latest on ci's test matrix platform
> Exclude fuse from windows build

- core/store/store.go
Fixes the issue in the image below when running daemon on windows:
> Fix: Truncate Badger Data logs on windows

- app/app.go
- core/sync/sync.go
- core/textile/buckd.go
- core/textile/bucket_factory.go
- core/textile/client.go
- core/textile/collections.go
This should fix some timing related issues that are being seen on some machines (I think more so on smaller ones). It's not final because the right way to do it is to either get a channel from Textile or poll the port to see if its listening yet, but for now doing a `sleep` as a temp fix so hackathon users aren't blocked.
* Make `buckd` wait for ready signal before moving on the next init
* Disable listing buckets in the syncer (this is also causing issues so disabling it until we resolve it - assumed this was okay because the listener was already partly commented out)
* Check for errors in a few places we should have been that were swallowing up errors
* Use `localhost` instead of `127.0.0.1` for bucket client to avoid wierd ipv6/name resolution errors (I think)
* If Textile doesn't have …
> Hotfix: misc timing issues

- core/textile/client.go
- core/textile/hub/hub_auth.go
- go.sum
Refactored temporary hub context helper to return context instead of token since it requires the API sig context embedded into it as well.
> Hotfix: Error on startup due to hub context issue

- core/textile/client.go
- core/textile/hub/hub_auth.go
Was investigating @gpuente 's issue on the binary failing if the envs weren't there which was incorrect since they should already be injected into the binary.  Looks like these 2 fields were still being brought in by env vars directly instead of the config file.
> Hotfix: use cfg values for txl hub key and secret

- app/app.go
The issue is that any `RunAsync()` `func` silently blocks the `app.Start()` on error, ie:
```golang
func (a *App) RunAsync(name string, component core.AsyncComponent, fn func() error) {
[...]
a.eg.Go(func() error {
return fn()
})
<-component.WaitForReady()
```
but:
```golang
func (tb *TextileBuckd) Start(ctx context.Context) error {
[...]
usr, err := user.Current()
if err != nil {
return err
}
[...]
tb.IsRunning = true
tb.Ready <- true
return nil
}
```
Also, we're not showing any error returned by `RunAsync()` `func`.
The pull request aims to fix both.
> don't block <-component.WaitForReady() on err

- cmd/space-daemon/main.go
- core/util/rlimit/rlimit_unix.go
- core/util/rlimit/rlimit_windows.go
- go.sum
Was trying to fix the `too many open files` error. Followed some leads and saw this https://docs.mongodb.com/manual/reference/ulimit/#:~:text=Most%20UNIX%2Dlike%20operating%20systems,using%20too%20many%20system%20resources and this https://github.com/ipfs/go-ipfs/issues/4589#issuecomment-358746222
After setting ulimit to a very high value, the problem seemed to be fixed. In this PR I am setting the ulimit value to the maximum possible on startup. Need further testing in other machines.
[ch18171]
> Set ulimit on start

- app/app.go
- core/textile/client.go
- core/textile/mailbox.go
- core/textile/mailbox_test.go
- grpc/handlers_sharing.go
Updates:
* inject hubAuth from the top app.go
* decode hex string properly
* use hub context when sending msg
* update mailbox tests
> Hotfix/sharing: A couple fixes to make create-share work

- core/space/services/services_sharing.go
This is so the FE doesn't have to send the repeated "personal" bucket name for each element in the paths on input (but we still need to have the field on a per path basis because for shared-with-me items they can vary file to file).
> Hotfix/sharing: just like dbid, this makes bucket optional for default buckets

- core/textile/bucket/bucket.go
- core/textile/bucket/bucket_dir.go
- core/textile/bucket/crypto/crypto.go
- core/textile/bucket/crypto/crypto_test.go
- core/textile/bucket/crypto/decrypter.go
- core/textile/bucket/crypto/encrypter.go
- core/textile/bucket_factory.go
- core/textile/collections.go
- core/textile/common/common.go
- core/textile/secure_bucket_client.go
- core/textile/utils/utils.go
- go.mod
**Update**
Now instead of path level encryption keys, we maintain a single encryption key for a bucket and that is re-used to encrypt all paths and their file contents before pushing to IPFS.
**CHANGELOG**
- Add EncryptionKey to bucket schema
- Abstraction around encrypting and decrypting bucket items
- Encrypt and Decrypt ListPath data [ch17961]
- Encrypt and Decrypt PushPath data [ch17942] & [ch17955]
- Encrypt and Decrypt RemovePath data [ch17968]
- Decrypt PullPath data before writing it back [ch17966]
Test include a unit test for the core encryption and decryption logic and for now did manual tests for the critical paths:
- Create a new bucket
- Create a directory
- List created directories and verify contents
- Uploaded a local file
- Fetched/Pulled the file from remote and it shows …
> Feature:  Bucket Level Encryption

- core/textile/bucket_factory.go
- core/textile/mirror.go
- core/textile/model/mirror_file.go
* Create mirror thread function
* Use mirror thread context for file and bucket mirror ops,
* Move encryption context to underlying `getBucketContext` function so it can be reused
> Hotfix/mirror-bucket: ctx related tweaks

- core/textile/client.go
- core/textile/mirror.go
* Create mirror thread was missing hub ctx so fixed that
* Moved `initialize`to after hub connection start to avoid race condition
NOTE: this means that a hub connection is required to init for now.  I think this is okay to release and then we can have a better online vs offline state management work started asap in parallel (i.e., what happens if they are offline during init? and then what happens if they come back online post init and vice versa).
> Hotfix/mirror: fix create mirror on init

- core/textile/mirror.go
- core/textile/model/mirror_file.go
- `UploadFileToHub` was calling get bucket context with some params swapped
- DbId casting issue
- Were not saving remote bucket key which was needed for lookup
- `FindMirrorFileByPathAndBucketSlug` - don't throw error on not found, instead return empty object (so it doesn't break creation)
- Use `cfg` value instead of OS environ directly for mirror hub addr
> Hotfix/mirror: fixes a few bugs in the mirror bucket and mirror file creation

- core/textile/sharing.go
- grpc/handlers_sharing.go
* Don't throw if members query throws (this is a temp fix and can be removed once we fix on textile side)
* Fix members list not showing properly
* Fix formatting for size and date fields
> Hotfix/receivedfiles: handle error and formatting

- grpc/handlers_notif.go
This bug was sending an empty path item before any real path items.
> Hotfix/notifs: dont send extra path item

- core/space/services/services_keypair.go
- core/space/services/services_vault.go
- core/space/space_test.go
- core/textile/client.go
- core/textile/textile.go
- mocks/Client.go
- Solve bug ch18273 where the clientside was requesting stuff from textile client before it was ready (right after account seeding).
[ch18273]
> Make key generation / restore ops wait for initialization of textile

- .github/workflows/release.yml
- README.md
This dynamically sets some secrets to have an env/stage suffix, i.e., `_DEV` or `_PRD`. It will always use `_PRD` unless the tag ends in `-dev`.  So for example tag `v0.0.15` will use PRD values, while `v0.0.15-dev` will use DEV values.
DEV secrets have already been added To GH.  Once this is approved I will update the existing ones to end in `_PRD` for those secrets that apply.
See README section on CI Secrets for more information.
> Stage specific secrets for CI

- .goreleaser.yml
- core/keychain/keychain.go
- Removed the `CGO_ENABLED=0` env in goreleaser, which was breaking up keychain on runtime. Weird thing is that if I do `CGO_ENABLED=1` it crashes on compilation (as goreleaser does not support CGO). So not sure why removing the env is both fixing the keychain issue and not crashing goreleaser. But anyways, tested a release (v0.0.16-dev) and it completes successfully and fixes the keychain segfault. Tested common daemon operations and they were all working.
[ch18315]
> Remove CGO_ENABLED env

- core/textile/bucket_factory.go
- core/textile/secure_bucket_client.go
- Fix decryption of shared files which was missing decrypting the root item when doing `ListPath` of the buckets client.
- Fix a bug I noticed where the textile client never got initialized because ListBuckets was erroring on the mirror bucket.
[ch18274]
> Fix list files decryption

- core/space/services/services_fs.go
Fixes this partially https://app.clubhouse.io/terminalsystems/story/18342/bug-accepting-a-notifcation-causes-space-daemon-crashes.
This fixes it so it at least doesn't crash.  But there is still some other error going on if we are landing at that case because that means mirror file wasn't found.
> Hotfix/files: dont crash on missing map entry.

- core/textile/sharing.go
Fixes the following wrong values for the wrong fields in the `members`:
```
"members": [
{
"publicKey": "",
"address": "bbaareifnrgcgvevcwepn7opqkr2ynjhgavwf5fpebdl3fnzwp6ajv2i6q4"
}
],
```
> members: unmarshal pubk and derive address

- core/space/services/services_fs.go
- core/textile/bucket_factory.go
- core/textile/secure_bucket_client.go
- examples/textileBucketsClient/open-share-file/open-share-file.go
* Before it was failing with `user does not own thread` because we were calling `list` buckets but the receiver doesn't have permissions to list all buckets since they only got shared a file (instead of listing all buckets, we now just fetch the path that was shared, and use it's `GetRoot` func to get the bucket root)
* A leftover log that was accessing an array item that was outside the index range - removed that altogether since it was just used for logging
* Added example of sharing and accessing file that helped isolate the issue
> Hotfix/sharing: bugs related to opening received file

- core/space/domain/domain.go
- core/space/services/services_fs.go
- core/space/space_test.go
- core/textile/bucket/bucket.go
- core/textile/bucket/bucket_file.go
- core/textile/secure_bucket_client.go
- core/textile/sharing.go
- grpc/handlers.go
- grpc/handlers_sharing.go
- Fix [ch18444]: File extension for shared files
- Fix [ch18445]: Return `backedUp` as true for shared files
- Fix [ch18423]: Return `locallyAvailable` as true if files are available locally.
- Fix a bug in `textile/buckets/bucket_file` in the method `FileExists` where it was always returning false.
> Multiple bug fixes

- core/keychain/keychain.go
- core/space/services/sharing_utils.go
- core/textile/bucket_factory.go
- core/textile/mailbox.go
- core/textile/model/model.go
- core/textile/model/received_file.go
- core/textile/public.go
- core/textile/utils/utils.go
- grpc/handlers_notif.go
- mocks/Model.go
* Get received files by ID helper
* Make message parser handle multiple so we can keep message specific logic in there
* Add fetch of statuses for messages
* Also a couple bugs that was in the way of this working:
* Bug: notification ID was not being saved in received files
* Bug: GetThreadContext was not creating new token so if transitioning from hub to local it failed (hotfixed this for now but maybe in a future fix we can tie this back to the cached token and switch based on the passed in `threadsClient` host or something)
> Hotfix/ch18277: show accept/reject on invitations

- core/textile/sync/synchronizer.go
This will at least make other tasks complete, but until we can call `AddReplicator` against prd hub without any errors we need this.
> Hotfix: make backup on task parallelizable

- core/textile/bucket/bucket_dir.go
- core/textile/sync/restore.go
- Make the restore iterator use the actual file path instead of the ipfs path
> Make iterator fn use file path instead of ipfs path

- core/space/domain/domain.go
- core/space/services/services_search.go
- core/space/space.go
- core/textile/client.go
- core/textile/model/model.go
- core/textile/model/search.go
- core/textile/search.go
- core/textile/sharing.go
- core/textile/sync/sync.go
- core/textile/sync/synchronizer.go
- core/textile/sync/task-executors.go
- core/textile/sync/task.go
- grpc/handlers_search.go
- mocks/Model.go
**CHANGELOG**
- Creates a search index collection on the meta thread. The search collection is created when the daemon initialization `rpc` is called.
- Export functions to update, query, and delete items from the search index
**TODO**
> Feature: Search Files/Folders Implementation

- core/textile/client.go
```
goroutine 9970 [running]:
github.com/FleekHQ/space-daemon/core/textile.(*textileClient).initialize(0xc009d987e0, 0x6ab8720, 0xc000562400, 0x0, 0x0)
/Users/maurycy/src/space-daemon/core/textile/client.go:400 +0x150
github.com/FleekHQ/space-daemon/core/textile.(*textileClient).healthcheck(0xc009d987e0, 0x6ab8720, 0xc000562400)
/Users/maurycy/src/space-daemon/core/textile/client.go:474 +0x2e0
github.com/FleekHQ/space-daemon/core/textile.(*textileClient).start(0xc009d987e0, 0x6ab8720, 0xc000562400, 0x6aac8e0, 0xc000194b80, 0x5caf100, 0x5f98680)
/Users/maurycy/src/space-daemon/core/textile/client.go:232 +0x59e
github.com/FleekHQ/space-daemon/core/textile.(*textileClient).Start(...)
/Users/maurycy/src/space-daemon/core/textile/client.go:418 …
```
> Fix a tc.sync.NotifyBucketStartup() SIGSEGV

- core/space/services/services_search.go
- core/textile/model/search.go
**CHANGELOG**
- Fixes file extension indexing `.` with extensions.
- Trim's prefix path separators returns with search path results.
> Fix: Search Index Extension and Result Path trimming

- core/textile/secure_bucket_client.go
For some reason `ioutil.TempFile` didn't like the encrypted file path here. Possible due to slashes/weird characters getting in the way. The fix just calculates a sha256 of the encrypted file name so it is somewhat normalized as far as characters go but still unique.
> Hotfix: opening file inside a subfolder instead of root

- config/map_config.go
- core/search/sqlite/sqlite.go
The pull request fixes the following error:
```
ERRO[0169] Error initializing files search index -- ERROR -- failed to open database: unable to open database file: no such file or directory[]
```
The tilde is replaced in `Start()` instead of `NewSearchEngine()` because the latter returns only `*sqliteFilesSearchEngine`, without the `err`, and the former is called only once anyway.
> sqlite: use usr.HomeDir

- core/space/services/services_fs.go
**CHANGELOG**
- When getting a reference to a temp file on the OpenFile() rpc call, the reference is no closed (leaks) and causes windows to prevent editing the file.
> Fix: Close Temp File after open for info

- Makefile
- README.md
- cmd/space-daemon/main.go
- core/space/services/services_sharing.go
- core/textile/bucket/bucket_file.go
- core/textile/client.go
- core/textile/public.go
- go.mod
- go.sum
- grpc/handlers_sharing.go
- tracing/tracing.go
**CHANGELOG**
- Setup tracing with jaegar and collect trace information on the `GeneratePublicFileLink` rpc
- Create default public share bucket on textile client initialization to prevent initialization during first time of sharing (should at least speed up some)
**Details of issue**
Uploads are still slow and tracing (see image below) shows that it take a long time while uploading to the bucket. The example in the image was a 3.5MB file and it took ~7mins to upload.
- It looks like uploads on the hub are actually quite slow (and I don't think it is only public bucket).
> Fix: Speed up public link generation

- core/search/bleve/bleve.go
- core/search/bleve/bleve_test.go
Reference: [ch19766]
**CHANGELOG**
- Update files search query to perform wildcard (prefix/suffix) search on files and folders.
- Setup proper mapping for index to ignore noisy fields when searching for records (to avoid irrelevant results).
> Feature: Improve infix search on files search

- core/space/services/services_fs.go
- core/space/space_test.go
This pull request fixes the issue caused by Snap mounting the app in a read-only filesystem:
```
time="2020-11-20t11:53:03-05:00" level=error msg="cannot create temp file while executing openfile -- error -- open /tmp/.mount_space-clg6kd/resources/329259853-space.png: read-only file system[]"
OPEN_ERROR_EVENT {
code: 2,
message: 'open /tmp/.mount_space-Clg6KD/resources/329259853-space.png: read-only file system',
metadata: {
'access-control-expose-headers': 'Grpc-Status, Grpc-Message, Date, Vary, Content-Type, grpc-status, grpc-message',
'content-type': 'application/grpc-web-text',
'grpc-message': 'open /tmp/.mount_space-Clg6KD/resources/329259853-space.png: read-only file system',
'grpc-status': '2',
vary: 'Origin',
connection: 'close',
'transfer-encoding': 'chunked'
}
}
```
> use a temporary directory for opening files
